name: Docker Extension for Meshery
on:
  workflow_call:
  # push:
  #   tags:
  #     - "v*"
  workflow_dispatch:
    inputs:
      release-ver:
        description: "Stable Release Version"
        required: true
        default: "v"
      stripped-release-ver:
        description: "Stripped Stable Release Version"
        required: true
        default: ""
      release-channel:
        description: "Release Channel"
        required: true
        default: "edge"

env:
  GIT_VERSION: ${{github.event.inputs.release-ver}}
  GIT_STRIPPED_VERSION: ${{github.event.inputs.stripped-release-ver}}
  RELEASE_CHANNEL: ${{github.event.inputs.release-channel}}
  GIT_TAG: ${{ github.event.release.tag_name }}

jobs:
  print-inputs:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "Dispatched GIT_VERSION: ${{github.event.inputs.release-ver}}"
          echo " Dispatched GIT_STRIPPED_VERSION: ${{github.event.inputs.stripped-release-ver}}"
          echo "Env RELEASE_CHANNEL: ${{env.RELEASE_CHANNEL}}"
          echo "Env GIT_VERSION: ${{env.GIT_VERSION}}"
          echo "Env GIT_STRIPPED_VERSION: ${{env.GIT_STRIPPED_VERSION}}"
          echo "Env GIT_TAG: ${{ github.event.release.tag_name }}"

  

