name: Meshery Build and Releaser (stable)
on:
  push:
    tags:
      - "v*"

jobs:
  call-dde-release-workflow:
    name: Build and Release Docker Extension
    uses: meshery/meshery/.github/workflows/build-and-release-dde.yml@master
    secrets: inherit
